server:
  port: 8080

spring:
  application:
    name: customers
#  kafka:
#    bootstrap-servers: localhost:9090
  datasource:
    url: jdbc:postgresql://localhost:5433/customers
    username: 'mindgarden'
    password: 'password'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL=DEBUG:
#zipkin:
#  base-url
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
